Repository scalar-labs/scalardb-samples, pull requests merged in 2023-06, with the labels that each got.

#31 Revise ScalarDB Sample
  scalardb-sample/README.md
  scalardb-sample/database-docker.properties
  scalardb-sample/docker-compose.yml
Labels: improvement

#32 Use Schema Loader jar to load schema in ScalarDB GraphQL Sample
  scalardb-graphql-sample/README.md
  scalardb-graphql-sample/database.properties
  scalardb-graphql-sample/docker-compose.yml
  scalardb-graphql-sample/graphql-server-database.properties
Labels: improvement

#33 Revise Multi-storage Transaction Sample
  multi-storage-transaction-sample/README.md
  multi-storage-transaction-sample/database-docker.properties
  multi-storage-transaction-sample/docker-compose.yml
  multi-storage-transaction-sample/wait-for-it.sh
Labels: improvement

#34 Add ScalarDB SQL (JDBC) Sample
  README.md
  scalardb-sql-jdbc-sample/README.md
  scalardb-sql-jdbc-sample/build.gradle
  scalardb-sql-jdbc-sample/docker-compose.yml
  scalardb-sql-jdbc-sample/gradle/wrapper/gradle-wrapper.jar
  scalardb-sql-jdbc-sample/gradle/wrapper/gradle-wrapper.properties
  scalardb-sql-jdbc-sample/gradlew
  scalardb-sql-jdbc-sample/gradlew.bat
  scalardb-sql-jdbc-sample/images/ERD.png
  scalardb-sql-jdbc-sample/scalardb-sql.properties
  scalardb-sql-jdbc-sample/schema.sql
  scalardb-sql-jdbc-sample/settings.gradle
  scalardb-sql-jdbc-sample/src/main/java/sample/Sample.java
  scalardb-sql-jdbc-sample/src/main/java/sample/command/GetCustomerInfoCommand.java
  scalardb-sql-jdbc-sample/src/main/java/sample/command/GetOrderCommand.java
  scalardb-sql-jdbc-sample/src/main/java/sample/command/GetOrdersCommand.java
  scalardb-sql-jdbc-sample/src/main/java/sample/command/LoadInitialDataCommand.java
  scalardb-sql-jdbc-sample/src/main/java/sample/command/PlaceOrderCommand.java
  scalardb-sql-jdbc-sample/src/main/java/sample/command/RepaymentCommand.java
  scalardb-sql-jdbc-sample/src/main/java/sample/command/SampleCommand.java
Labels: enhancement

#36 Use SQL CLI to load schema in Spring Data JDBC for ScalarDB samples
  multi-storage-transaction-sample/README.md
  scalardb-graphql-sample/README.md
  scalardb-sample/README.md
  spring-data-multi-storage-transaction-sample/README.md
  spring-data-multi-storage-transaction-sample/docker-compose.yml
  spring-data-multi-storage-transaction-sample/scalardb-sql.properties
  spring-data-multi-storage-transaction-sample/schema.json
  spring-data-multi-storage-transaction-sample/schema.sql
  spring-data-multi-storage-transaction-sample/wait-for-it.sh
  spring-data-sample/README.md
  spring-data-sample/docker-compose.yml
  spring-data-sample/scalardb-sql.properties
  spring-data-sample/schema.json
  spring-data-sample/schema.sql
  spring-data-sample/wait-for-it.sh
Labels: improvement

#38 Add another way to specify GitHub username and personal access token with environment variables to SQL samples
  scalardb-sql-jdbc-sample/README.md
  spring-data-multi-storage-transaction-sample/README.md
  spring-data-sample/README.md
Labels: documentation

#39 Update gradle version to support latest Java version
  microservice-transaction-sample/gradle/wrapper/gradle-wrapper.properties
  multi-storage-transaction-sample/gradle/wrapper/gradle-wrapper.properties
  scalardb-sample/gradle/wrapper/gradle-wrapper.properties
  scalardb-server-sample/gradle/wrapper/gradle-wrapper.properties
  scalardb-sql-jdbc-sample/gradle/wrapper/gradle-wrapper.properties
  spring-data-multi-storage-transaction-sample/gradle/wrapper/gradle-wrapper.properties
  spring-data-sample/gradle/wrapper/gradle-wrapper.properties
Labels: improvement

#40 Revise README of Spring Data JDBC for ScalarDB with microservice
  spring-data-microservice-transaction-sample/README.md
Labels: documentation

#41 Add "Spring Data JDBC for ScalarDB with microservice transaction" sample to top-level README
  README.md
Labels: documentation
